//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsServiceProxy
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ProtocolloWebService", ConfigurationName="WsServiceProxy.ProtocolloWebService")]
    public interface ProtocolloWebService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="protocollaReturn")]
        WsServiceProxy.DocumentoProtocollato protocolla(WsServiceProxy.WSAuthentication authentication, WsServiceProxy.DocumentoProtocollato documentoProtocollato);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="protocollaReturn")]
        System.Threading.Tasks.Task<WsServiceProxy.DocumentoProtocollato> protocollaAsync(WsServiceProxy.WSAuthentication authentication, WsServiceProxy.DocumentoProtocollato documentoProtocollato);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ws.example")]
    public partial class WSAuthentication
    {
        
        private string aooField;
        
        private string applicazioneField;
        
        private string enteField;
        
        private string passwordField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string aoo
        {
            get
            {
                return this.aooField;
            }
            set
            {
                this.aooField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string applicazione
        {
            get
            {
                return this.applicazioneField;
            }
            set
            {
                this.applicazioneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ente
        {
            get
            {
                return this.enteField;
            }
            set
            {
                this.enteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://ws.example")]
    public partial class WSEsito
    {
        
        private string codiceEsitoField;
        
        private string descrizioneEsitoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codiceEsito
        {
            get
            {
                return this.codiceEsitoField;
            }
            set
            {
                this.codiceEsitoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descrizioneEsito
        {
            get
            {
                return this.descrizioneEsitoField;
            }
            set
            {
                this.descrizioneEsitoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://type.ws.example")]
    public partial class DocumentoProtocollato
    {
        
        private byte[] contenutoField;
        
        private System.Nullable<System.DateTime> dataDocumentoField;
        
        private WSEsito esitoField;
        
        private System.Nullable<long> idField;
        
        private bool isContenutoField;
        
        private string nomeFileContenutoField;
        
        private string numeroProtocolloField;
        
        private string oggettoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] contenuto
        {
            get
            {
                return this.contenutoField;
            }
            set
            {
                this.contenutoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataDocumento
        {
            get
            {
                return this.dataDocumentoField;
            }
            set
            {
                this.dataDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public WSEsito esito
        {
            get
            {
                return this.esitoField;
            }
            set
            {
                this.esitoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<long> id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public bool isContenuto
        {
            get
            {
                return this.isContenutoField;
            }
            set
            {
                this.isContenutoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nomeFileContenuto
        {
            get
            {
                return this.nomeFileContenutoField;
            }
            set
            {
                this.nomeFileContenutoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string numeroProtocollo
        {
            get
            {
                return this.numeroProtocolloField;
            }
            set
            {
                this.numeroProtocolloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string oggetto
        {
            get
            {
                return this.oggettoField;
            }
            set
            {
                this.oggettoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ProtocolloWebServiceChannel : WsServiceProxy.ProtocolloWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ProtocolloWebServiceClient : System.ServiceModel.ClientBase<WsServiceProxy.ProtocolloWebService>, WsServiceProxy.ProtocolloWebService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ProtocolloWebServiceClient() : 
                base(ProtocolloWebServiceClient.GetDefaultBinding(), ProtocolloWebServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ProtocolloWebService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProtocolloWebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ProtocolloWebServiceClient.GetBindingForEndpoint(endpointConfiguration), ProtocolloWebServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProtocolloWebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ProtocolloWebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProtocolloWebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ProtocolloWebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProtocolloWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public WsServiceProxy.DocumentoProtocollato protocolla(WsServiceProxy.WSAuthentication authentication, WsServiceProxy.DocumentoProtocollato documentoProtocollato)
        {
            return base.Channel.protocolla(authentication, documentoProtocollato);
        }
        
        public System.Threading.Tasks.Task<WsServiceProxy.DocumentoProtocollato> protocollaAsync(WsServiceProxy.WSAuthentication authentication, WsServiceProxy.DocumentoProtocollato documentoProtocollato)
        {
            return base.Channel.protocollaAsync(authentication, documentoProtocollato);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProtocolloWebService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProtocolloWebService))
            {
                return new System.ServiceModel.EndpointAddress("http://example.url/ProtocolloWebService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ProtocolloWebServiceClient.GetBindingForEndpoint(EndpointConfiguration.ProtocolloWebService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ProtocolloWebServiceClient.GetEndpointAddress(EndpointConfiguration.ProtocolloWebService);
        }
        
        public enum EndpointConfiguration
        {
            
            ProtocolloWebService,
        }
    }
}
